// react-app/src/pages/Login.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { auth } from '../utils/auth';
import Toast from '../components/Toast';
import './Auth.css';

export default function Login() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({ email: '', password: '' });
  const [errors, setErrors] = useState({});
  const [toast, setToast] = useState(null);

  const validate = () => {
    const newErrors = {};
    if (!formData.email) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Email is invalid';
    }
    if (!formData.password) {
      newErrors.password = 'Password is required';
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;

    const result = await auth.login(formData.email, formData.password);
    if (result.success) {
      setToast({ message: 'Login successful!', type: 'success' });
      setTimeout(() => navigate('/dashboard'), 1000);
    } else {
      setToast({ message: result.error, type: 'error' });
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-container card">
        <h1>Welcome Back</h1>
        <p className="auth-subtitle">Sign in to your account</p>
        
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="email" className="form-label">Email</label>
            <input
              id="email"
              type="email"
              className="form-input"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              aria-label="Email address"
            />
            {errors.email && <div className="error-message">{errors.email}</div>}
          </div>

          <div className="form-group">
            <label htmlFor="password" className="form-label">Password</label>
            <input
              id="password"
              type="password"
              className="form-input"
              value={formData.password}
              onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              aria-label="Password"
            />
            {errors.password && <div className="error-message">{errors.password}</div>}
          </div>

          <button type="submit" className="btn btn-primary">Login</button>
        </form>

        <p className="auth-link">
          Don't have an account? <Link to="/auth/signup">Sign up</Link>
        </p>

        
      </div>

      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
    </div>
  );
}

// vue-app/src/views/Login.vue
<script setup>
import { ref } from 'vue';
import { RouterLink, useRouter } from 'vue-router';
import { auth } from '../utils/auth';
import Toast from '../components/Toast.vue';

const router = useRouter();
const formData = ref({ email: '', password: '' });
const errors = ref({});
const toast = ref(null);

const validate = () => {
  const newErrors = {};
  if (!formData.value.email) {
    newErrors.email = 'Email is required';
  } else if (!/\S+@\S+\.\S+/.test(formData.value.email)) {
    newErrors.email = 'Email is invalid';
  }
  if (!formData.value.password) {
    newErrors.password = 'Password is required';
  }
  errors.value = newErrors;
  return Object.keys(newErrors).length === 0;
};

const handleSubmit = async (e) => {
  e.preventDefault();
  if (!validate()) return;

  const result = await auth.login(formData.value.email, formData.value.password);
  if (result.success) {
    toast.value = { message: 'Login successful!', type: 'success' };
    setTimeout(() => router.push('/dashboard'), 1000);
  } else {
    toast.value = { message: result.error, type: 'error' };
  }
};
</script>

<template>
  <div class="auth-page">
    <div class="auth-container card">
      <h1>Welcome Back</h1>
      <p class="auth-subtitle">Sign in to your account</p>
      
      <form @submit="handleSubmit">
        <div class="form-group">
          <label for="email" class="form-label">Email</label>
          <input
            id="email"
            type="email"
            class="form-input"
            v-model="formData.email"
            aria-label="Email address"
          />
          <div v-if="errors.email" class="error-message">{{ errors.email }}</div>
        </div>

        <div class="form-group">
          <label for="password" class="form-label">Password</label>
          <input
            id="password"
            type="password"
            class="form-input"
            v-model="formData.password"
            aria-label="Password"
          />
          <div v-if="errors.password" class="error-message">{{ errors.password }}</div>
        </div>

        <button type="submit" class="btn btn-primary">Login</button>
      </form>

      <p class="auth-link">
        Don't have an account? <RouterLink to="/signup">Sign up</RouterLink>
      </p>

      <!-- <div class="demo-credentials">
        <p><strong>Demo Credentials:</strong></p>
        <p>Email: demo@example.com</p>
        <p>Password: password123</p>
      </div> -->
    </div>

    <Toast v-if="toast" :message="toast.message" :type="toast.type" @close="toast = null" />
  </div>
</template>

<style src="../assets/styles/Auth.css"></style>
