// vue-app/src/components/Toast.vue
<script setup>
import { onMounted, onUnmounted } from 'vue';

const props = defineProps({
  message: String,
  type: String
});

const emit = defineEmits(['close']);

let timer;

onMounted(() => {
  timer = setTimeout(() => {
    emit('close');
  }, 3000);
});

onUnmounted(() => {
  if (timer) clearTimeout(timer);
});
</script>

<template>
  <div :class="['toast', type]">
    {{ message }}
  </div>
</template>

// react-app/src/components/Toast.jsx
import { useEffect } from 'react';

export default function Toast({ message, type, onClose }) {
  useEffect(() => {
    const timer = setTimeout(() => {
      onClose();
    }, 3000);
    return () => clearTimeout(timer);
  }, [onClose]);

  return (
    <div className={`toast ${type}`}>
      {message}
    </div>
  );
}
